### ISSUE TITLE
Can't load file on OSX

### ISSUE THREAD

**Issue by n1c** [lxteo/Cities-Skylines-Mapper#1]
Hello!

I tried to get the mod working but just end up getting an error when trying to load the map file; is it possible that the backslash here [https://github.com/lxteo/Cities-Skylines-Mapper/blob/master/Mapper/Panels/MapperWindow.cs#L114] should be a forward slash on OSX?

Thanks!

**Comment by lxteo** [comment]
You can replace the text in the textbox with the correct path, does that work?

**Comment by n1c** [comment]
Ah I unsubscribed & resub'd and looks like I must have been on an old version and it came alive. Not having a cursor in the input thew me off :smile:
