### ISSUE TITLE
Proejct License

### ISSUE THREAD

**Issue by rdiekema** [lxteo/Cities-Skylines-Mapper#4]
Can a license be added to the project or source files so that forks of this repository know what they may do with your work?

Having the source public and being open source are two very different things, and I'd like to publish the OSM import functionality as a standalone mod.

Thank you.

**Comment by lxteo** [comment]
Oops, just added the license.

Although I don't know if that's even legal, since the whole thing belongs to Paradox and is sort of a grey area where Paradox has just sort of pinkie promised not to go after anyone who reverse engineers the game.
